### ISSUE TITLE
SSH keys for CI

### ISSUE THREAD

**Issue by sglyon** [plotly/plotlyjs.jl-docs#13]
Build is failing to push to the repo. Looks like it is an issue with keys and permissions 

https://app.circleci.com/pipelines/github/plotly/plotlyjs.jl-docs/37/workflows/b3f3daf9-12c5-46af-9625-d12da1b5b9c0/jobs/39/parallel-runs/0/steps/0-106

**Comment by nicolaskruchten** [comment]
Success! https://github.com/plotly/plotlyjs.jl-docs/tree/built

Thanks muchly. I just had to actually add @plotlydocbot to this repo as a writer.
