### ISSUE TITLE
Missing a "Getting Started" page

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotlyjs.jl-docs#15]
From the list in https://github.com/plotly/plotlyjs.jl-docs/issues/2 I think we're missing a "Getting Started" page that describes how to install PlotlyJS.jl. I can't deploy these docs without it because our current page describes how to install Plotly.jl :)

**Comment by nicolaskruchten** [comment]
OK I lied, I *can* deploy (and I did! https://plotly.com/julia/) but we should still get an updated Getting Started page ;)

**Comment by nicolaskruchten** [comment]
Looks great in prod! All done for the initial build-out! ✅

**Comment by sglyon** [comment]
Excellent!!
