### ISSUE TITLE
Bulleted lists

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotlyjs.jl-docs#16]
Bulleted lists in the Markdown input aren't showing up as bulleted in the browser because there's a nested `<p>` tag in the `<li>`.

**Comment by nicolaskruchten** [comment]
See for example the bulleted lists at the top of https://plotly.com/julia/axes/

**Comment by sglyon** [comment]
Just looked into this and from what I can tell it is an issue with the CSS on the page.

There is this definition in the css

```css
ul {
  margin: 0;
  padding: 0;
  list-style-type: none; }
```

The `list-style-type: none` is causing the bullets to not render. 

I noticed that there is also a rule for `list-style-type: disc` that is overridden by the `none` version:

![Screenshot_20210819_102230](https://user-images.githubusercontent.com/1001948/130085713-68b23839-e471-43a3-b48e-c3407d1cc8cf.png)

**Comment by sglyon** [comment]
The python side adds classes `rendered` and `rendered_html` to many of the output divs -- this brings back the bullets.

One solution would be for us to add those classes to the output also

**Comment by sglyon** [comment]
![Screenshot_20210819_104129](https://user-images.githubusercontent.com/1001948/130088878-3046dc9e-b1fa-4c5f-abdb-6f2a75d664b5.png)

**Comment by nicolaskruchten** [comment]
yeah if you could try to match the nbconvert output that'd be helpful. I don't have a ton of time atm to tune the host CSS for a new flavour of HTML fragment :)

**Comment by nicolaskruchten** [comment]
Looks great in prod, thanks!
