### ISSUE TITLE
Full list of Julia docs to port

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotlyjs.jl-docs#2]
In order for us to fully replace the existing plotly.com/julia docs with the contents of this repo, we'll need to port every page from https://github.com/plotly/graphing-library-docs/tree/master/_posts/julia into this repo, and specifically, we'll need a matching page here for every URL.

running `cat */*html | grep permalink` in that directory lists all the links we'll need a page for in this repo, so that can serve a punch-list for the work to do:

- [x] julia/3d-line-plots/
- [x] julia/3d-scatter-plots/
- [x] julia/3d-surface-plots/
- [ ] julia/text-and-annotations/
- [ ] julia/filled-area-plots/
- [ ] julia/axes/
- [x] julia/bar-charts/
- [x] julia/box-plots/
- [x] julia/bubble-charts/
- [x] julia/contour-plots/
- [x] julia/error-bars/
- [x] ~julia/file-options/~
- [ ] julia/font/
- [ ] julia/getting-started/
- [x] julia/heatmaps/
- [x] julia/histograms/
- [x] julia/2D-Histogram/
- [ ] julia/embedding-plotly-graphs-in-HTML/
- [x] julia/insets/
- [ ] julia/figure-labels/
- [ ] julia/LaTeX/
- [ ] julia/legend/
- [x] julia/line-and-scatter/
- [x] julia/log-plot/
- [x] julia/graphing-multiple-chart-types/
- [x] julia/multiple-axes/
- [x] julia/polar-chart/
- [x] ~julia/privacy/~
- [ ] julia/setting-graph-size/
- [x] julia/subplots/
- [x] julia/time-series

**Comment by nicolaskruchten** [comment]
I want to call special attention to the `/julia/getting-started` docs as being something you'll want to put a lot of care into to make sure folks get off to a good start :)

**Comment by nicolaskruchten** [comment]
Note: please omit anything related to our Chart Studio product, like /privacy and /file-settings and any others I've missed :)

**Comment by sglyon** [comment]
Awesome thanks for this list!

I think we have a really good start on this already. 

We'll work to get this buttoned up

**Comment by sglyon** [comment]
we did it!
