### ISSUE TITLE
CircleCI job

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotlyjs.jl-docs#4]
This repo will need a CircleCI job that runs the makefile and puts the output in a `built` branch in this repo, much like the job in the Python repo does: https://github.com/plotly/plotly.py/blob/09bbd7584a5cacc2d13e4fcaa6ae292d5ae03c1f/.circleci/config.yml#L301

This is the handoff point between this repo and the `graphing-library-docs` repo that handles the actual publishing to plotly.com/julia

**Comment by sglyon** [comment]
closed in #5  🎉
